# Generated by Django 5.1.3 on 2025-04-18 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1)),
                ('date_naissance', models.CharField(max_length=50)),
                ('photo', models.URLField(blank=True)),
                ('details', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('spouse', 'Conjoint'), ('parent', 'Parent')], max_length=20)),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_from', to='arbre.person')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_to', to='arbre.person')),
            ],
        ),
    ]
