# Generated by Django 5.1.3 on 2025-04-18 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbre', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='date_naissance',
            new_name='dateNaissance',
        ),
        migrations.AlterField(
            model_name='familyrelation',
            name='from_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='arbre.person'),
        ),
        migrations.AlterField(
            model_name='familyrelation',
            name='to_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='arbre.person'),
        ),
        migrations.AlterField(
            model_name='familyrelation',
            name='type',
            field=models.CharField(choices=[('spouse', 'Conjoint'), ('child', 'Enfant')], max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='genre',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='familyrelation',
            unique_together={('from_person', 'to_person', 'type')},
        ),
    ]
