# Generated by Django 5.1.3 on 2025-04-18 18:28

import arbre.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbre', '0002_rename_date_naissance_person_datenaissance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=arbre.models.person_photo_path, verbose_name='Photo de profil'),
        ),
    ]
