# Generated by Django 5.2 on 2025-05-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arbre", "0003_alter_person_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="familyrelation",
            name="rank",
            field=models.IntegerField(default=0),
        ),
    ]
